#!/bin/bash

pipeline {
    agent any

    environment {
         branch = '$selectBranch'
         deploy = '$deployEnv'
    }
    stages{
        stage('Enviroment'){
            steps{
                cat "./deploy/jenkins/\"$deploy\"/jenkinsfile"
            }
        }
    }
}
