#!/usr/bin/env groovy
pipeline {
    agent any
    parameters {
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'master', name: 'BRANCH', type: 'PT_BRANCH'
      }
      stages {
        stage('Example') {
          steps {
            git branch: "${params.BRANCH}", url: 'https://github.com/MarceloAraujo14/schedule-api.git'
          }
        }
      }
    stages {
        stage('clean') {
            steps {
                sh 'chmod +x gradlew'
                sh './gradlew clean'
            }
        }
        stage('test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('build') {
            steps {
                sh './gradlew build'
            }
        }
        stage('buildImage') {
            steps {
                sh './gradlew :bootBuildImage'
            }
        }
        stage('deploy') {
            steps {
                sh 'cd deploy/docker'
                sh 'docker-compose up -d'
            }
        }
    }
}